# Generated by Django 6.0 on 2025-12-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
